### ISSUE TITLE
NativeTextInputDialog - Android  - Error

### ISSUE THREAD

**Issue by epartipilo** [mateuszmackowiak/NativeDialogs#24] opened 2013-06-13 12:57 UTC
Error on creating NativeTextInputDialog instance on Android. (iOS works fine)
![captura de pantalla 2013-06-13 a la s 14 58 28](https://f.cloud.github.com/assets/4688744/648373/01c2d304-d429-11e2-8920-30cb38551e51.png)

**Comment by mattmurton** [comment] 2013-06-19 21:25
Duplicate of https://github.com/mateuszmackowiak/NativeDialogs/issues/20 see my comment for a fixed version

**Closed as completed** 2013-07-09 23:15 UTC
