### ISSUE TITLE
Runtime error on android

### ISSUE THREAD

**Issue by GreenishFlow** [mateuszmackowiak/NativeDialogs#22] opened 2013-06-11 11:47 UTC
Hello.
When I start my app on android with using NativeDatePickerDialog (ios is good), the runtime error occurs:
[Fault] exception, information=Error: [pl.mateuszmackowiak.nativeANE.dialogs.NativeDatePickerDialog] Error initiating contex of the NativeDatePickerDialog extension: Error #1009: Cannot access a property or method of a null object reference.
at pl.mateuszmackowiak.nativeANE.dialogs.support::AbstractNativeDialog/showError()[/Users/mmmackowiak/Documents/git/NativeDialogs/AS/src/pl/mateuszmackowiak/nativeANE/dialogs/support/AbstractNativeDialog.as:259]
at pl.mateuszmackowiak.nativeANE.dialogs::NativeDatePickerDialog/init()[/Users/mmmackowiak/Documents/git/NativeDialogs/AS/src/pl/mateuszmackowiak/nativeANE/dialogs/NativeDatePickerDialog.as:148]
at pl.mateuszmackowiak.nativeANE.dialogs::NativeDatePickerDialog()[/Users/mmmackowiak/Documents/git/NativeDialogs/AS/src/pl/mateuszmackowiak/nativeANE/dialogs/NativeDatePickerDialog.as:140]
at com.agamobile.ui.layouts::ConversationPageLayout/onAdded()[D:\GreenishFlow_Works\fuel\AGA\flash\AGA-mobile\Classes\com\agamobile\ui\layouts\ConversationPageLayout.as:80]

my code is just:
var d:NativeDatePickerDialog = new NativeDatePickerDialog();
        d.addEventListener(NativeDialogEvent.CLOSED,onCloseDialog);
        d.addEventListener(NativeDialogEvent.CANCELED,trace);
        d.addEventListener(NativeDialogEvent.OPENED,trace);
        d.addEventListener(Event.CHANGE,onTimePicked);
        d.buttons = Vector.<String>(["Cancle","OK"]);
        d.displayMode = NativeDatePickerDialog.DISPLAY_MODE_TIME;
        d.title = "Pick the time for the Date";
        d.message = "Select time:";
        d.show(false);

Thanks

**Comment by mattmurton** [comment] 2013-06-12 14:13
Duplicate of https://github.com/mateuszmackowiak/NativeDialogs/issues/20 see my comment for a fixed version

**Closed as completed** 2013-07-09 23:15 UTC
